name: Deploy CDK Stack

on:
  push:
    branches:
      - main  # mainブランチへのプッシュで実行
  workflow_dispatch:  # 手動実行も可能

permissions:
  id-token: write  # OIDC認証に必要
  contents: read   # リポジトリ読み取り権限

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::185168971689:role/role-gha-awscdk-test  # 作成したロールのARN
          aws-region: ap-northeast-1  # デプロイするリージョン

      - name: Deploy with CDK
        run: npx cdk deploy --require-approval never
        
      - name: Test Lambda function
        run: |
          # Lambda関数名を取得（CDK出力から動的に取得するとよりロバストになります）
          LAMBDA_FUNCTION_NAME=$(aws cloudformation describe-stacks --stack-name MyLambdaS3Stack --query "Stacks[0].Outputs[?OutputKey=='LambdaFunctionName'].OutputValue" --output text)
          
          echo "Invoking Lambda function: $LAMBDA_FUNCTION_NAME"
          # Lambda関数を呼び出し、結果をファイルに保存
          aws lambda invoke --function-name $LAMBDA_FUNCTION_NAME --cli-binary-format raw-in-base64-out --payload '{"message": "Test from GitHub Actions"}' response.json
          
          # 結果を表示
          cat response.json